version: '3.1'

services:

  persifleur:
    image: registry.magnier.io/qsypoq/persifleur:latest
    restart: always
    ports:
      - 1337:1337
    volumes:
      - ./sources:/usr/src/app/sources
      - ./html:/usr/src/app/html
      - ./assets:/usr/src/app/assets
      - ~/.ssh:/root/.ssh

  httpd:
    image: httpd:latest
    restart: always
    ports:
      - 4444:80
    environment:
      VIRTUAL_HOST: www.magnier.io,magnier.io
      VIRTUAL_PORT: 4444
      LETSENCRYPT_HOST: www.magnier.io,magnier.io
      LETSENCRYPT_EMAIL: adam@magnier.io
      REGISTRAR: namecheap
      EXTERNAL_IP: 152.228.170.93
    volumes:
      - ./html:/usr/local/apache2/htdocs/
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf

networks:
   default:
     external:
       name: nginx-proxy
