name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login registry.magnier.io -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag registry.magnier.io/qsypoq/persifleur:latest

    - name: Docker Push
      run: docker push registry.magnier.io/qsypoq/persifleur:latest
      
    - name: Setup SSH
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{secrets.VPS_SRV}}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH }}
        port: 22
        script:  |
          ssh -o "StrictHostKeyChecking=no" ${{secrets.VPS_SRV}} "git -C ${{secrets.PREPROD_PATH}} pull && git -C ${{secrets.PROD_PATH}} pull"
          ssh -o "StrictHostKeyChecking=no" ${{secrets.VPS_SRV}} "cd ${{secrets.PREPROD_PATH}} && docker-compose -f docker-compose-preprod.yml rm -fs && docker-compose -f docker-compose-preprod.yml pull && docker-compose -f docker-compose-preprod.yml up -d"
